spring:
  datasource:
    url: jdbc:mysql://${DATABASE_SERVER_NAME:localhost}:3306/bookstore
    username: ${DATABASE_USER_NAME:java}
    password: ${DATABASE_USER_PASSWORD:1234}
  jpa:
    hibernate:
      # dont do this in production!!
      ddl-auto: update
  lifecycle:
    timeout-per-shutdown-phase: 30s
  flyway:
    url: jdbc:mysql://${DATABASE_SERVER_NAME:localhost}:3306/bookstore
    user: ${DATABASE_USER_NAME:java}
    password: ${DATABASE_USER_PASSWORD:1234}
    baseline-on-migrate: true

info:
  app:
    name: bookstore
    description: bookstore - a book api
management:
  endpoint:
    metrics:
      enabled: true
    health:
      probes:
        enabled: true
  endpoints:
    web:
      exposure:
        include: info,health,prometheus,metrics
server:
  shutdown: graceful
  servlet:
    context-path: /app